context("Print a skim_df object")

test_that("Skim prints a header for the entire output and each type", {
  input <- skim(iris)
  expect_output(print(input), "Skim summary statistics")
  expect_output(print(input), "n obs: 150")
  expect_output(print(input), "n variables: 5 \n")
  expect_output(print(input), "Variable type: factor")
  expect_output(print(input), "Variable type: numeric")
})

test_that("Skim prints a special header for grouped data frames", {
  input <- skim(dplyr::group_by(iris, Species))
  expect_output(print(input), " group variables: Species")
  expect_output(print(input), "n obs: 150")
  expect_output(print(input), "n variables: 5 \n")
})

test_that("Skim collapses counts and other multivalue stats into one cell", {
  input <- skim(iris)
  expect_output(print(skim, "set: 50, ver: 50, vir: 50, NA: 0"))
})

test_that("Skim aligns numeric vectors at the decimal point by default", {
  input <- skim(mtcars)
  expect_output(print(input), "  am       0       32 32   0.41   0.5   0")
  expect_output(print(input), "carb       0       32 32   2.81   1.62  1")
  expect_output(print(input), "drat       0       32 32   3.6    0.53  2.76")
  expect_output(print(input), "gear       0       32 32   3.69   0.74  3")
})

test_that("spark.print returns the correct result",{
  input <- inline_hist(chickwts$weight)
  expect_output(print(input), "▃▅▅▇▃▇▂▂")
  
})

test_that("Skimr kable  prints as expected", {
  skimmed <- skim(chickwts)
  input <-skimr::kable(skimmed)

  expect_output(print(input), "Variable type: factor")
  expect_output(print(input), "|variable |missing |complete |n   |n_unique |top_counts                       |ordered |")
  expect_output(print(input), "|:--------|:-------|:--------|:---|:--------|:--------------------------------|:-------|")
  expect_output(print(input), "|Species  |0       |150      |150 |3        |set: 50, ver: 50, vir: 50, NA: 0 |FALSE   |")
  expect_output(print(input), "Variable type: numeric")
  expect_output(print(input), "|variable     |missing |complete |n   |mean |sd   |min |p25 |median |p75 |max |hist     |")
  expect_output(print(input), "|:------------|:-------|:--------|:---|:----|:----|:---|:---|:------|:---|:---|:--------|")
  expect_output(print(input), "|Petal.Length |0       |150      |150 |3.76 |1.77 |1   |1.6 |4.35   |5.1 |6.9 |▇▁▁▂▅▅▃▁ |")
  expect_output(print(input), "|Petal.Width  |0       |150      |150 |1.2  |0.76 |0.1 |0.3 |1.3    |1.8 |2.5 |▇▁▁▅▃▃▂▂ |")
  expect_output(print(input), "|Sepal.Length |0       |150      |150 |5.84 |0.83 |4.3 |5.1 |5.8    |6.4 |7.9 |▂▇▅▇▆▅▂▂ |")
  expect_output(print(input), "|Sepal.Width  |0       |150      |150 |3.06 |0.44 |2   |2.8 |3      |3.3 |4.4 |▁▂▅▇▃▂▁▁ |")
})

test_that("skimr::pander prints as expected", {
  # This assumes the default option for line length (80).
  data(chickwts)
  input <- utils::capture.output(skim(chickwts) %>% skimr::pander() )
  expect_equal(length(input), 35)
  expect_equal(input[1], "")
  expect_equal(input[2], "Variable type: factor")
  expect_equal(input[3], "----------------------------------------------------------------------------")
  expect_equal(input[4], " variable   missing   complete   n    n_unique           top_counts         ")
  expect_equal(input[5], "---------- --------- ---------- ---- ---------- ----------------------------")
  expect_equal(input[6], "   feed        0         71      71      6       soy: 14, cas: 12, lin: 12, ")
  expect_equal(input[7], "                                                          sun: 12           ")
  expect_equal(input[8], "----------------------------------------------------------------------------")
  expect_equal(input[9], "")
  expect_equal(input[10], "Table: Table continues below")
  expect_equal(input[11], "")
  expect_equal(input[12], " ")
  expect_equal(input[13], "---------")
  expect_equal(input[14], " ordered ")
  expect_equal(input[15], "---------")
  expect_equal(input[16], "  FALSE  ")
  expect_equal(input[17], "---------")
  expect_equal(input[18], "")
  expect_equal(input[19], "")
  expect_equal(input[20], "Variable type: numeric")
  expect_equal(input[21], "----------------------------------------------------------------------------")
  expect_equal(input[22], " variable   missing   complete   n     mean     sd     min    p25    median ")
  expect_equal(input[23], "---------- --------- ---------- ---- -------- ------- ----- ------- --------")
  expect_equal(input[24], "  weight       0         71      71   261.31   78.07   108   204.5    258   ")
  expect_equal(input[25], "----------------------------------------------------------------------------")
  expect_equal(input[26], "")
  expect_equal(input[27], "Table: Table continues below")
  expect_equal(input[28], "")
  expect_equal(input[29], " ")
  expect_equal(input[30], "------------------------")
  expect_equal(input[31], "  p75    max     hist   ")
  expect_equal(input[32], "------- ----- ----------")
  expect_equal(input[33], " 323.5   423   ▃▅▅▇▃▇▂▂ ")
  expect_equal(input[34], "------------------------")
  expect_equal(input[35], "")
})
